[package]
name = "php-rs"
description = "Bindings for the Zend API to build PHP extensions natively in Rust."
repository = "https://github.com/davidcole1340/php-rs"
license = "MIT"
keywords = ["php"]
version = "0.1.0"
authors = ["David Cole <david.cole1340@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.88"
bitflags = "1.2.1"

[build-dependencies]
bindgen = "0.53.1"
regex = "1"
