name: Master Branch Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_lint:
    name: Build and Lint
    uses: ./.github/workflows/build.yml
  release:
    name: Create Release (MR)
    needs: [build_and_lint]
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-plz.yml
    secrets:
      RELEASE_PLZ_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
  docs:
    name: Build and Deploy Documentation
    needs: [release]
    if: needs.release.outputs.release_created == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/docs.yml
